### ISSUE TITLE
Add optional extra callback on/before "Fullfør i Vipps"-button to check if cart-value has been changed 

### ISSUE THREAD

**Issue by madsoliver** [vippsas/vipps-checkout-api#43]
There may be customers using multiple tabs when shopping. One tab might have opened the Vipps checkout allready, but in another tab, the customer might have added/removed products, causing Vipps transaction value not to be equal with the current cart value.

This should off course be handled in the merchants server, disallowing orders with unequal order-total and Vipps transaction value, BUT since this information comes AFTER the customer has fulfilled the order in Vipps, it's to late to do anything else than cancelling.

If we had a callback just before finalizing, then we could refresh the Vipps checkout iframe (reinitialize) if totals have changed, and then fullfill the order.

**Comment by Ceredron** [comment]
I apologize for late response to this.

We do not want to introduce a callback that would potentially block a payment due to performance, network or bug issues on the merchant's end. 

I think a better solution in this case would be for the merchant's order page to continuously poll their own backend for current cart amount and re-initialize the session if it has changed.
